### ISSUE TITLE
Add information about current status

### ISSUE THREAD

**Issue by homm** [ciotto/pyheif-pillow-opener#11]
Hi, @ciotto!

I'm one of the [Pillow developers](https://github.com/orgs/python-pillow/people) and I created a fork of this plugin with many bug fixes. It called [heif-image-plugin](https://github.com/uploadcare/heif-image-plugin/). Also I working on many changes in Pyheif and even some changes in libheif to ensure first-class HEIF images support in Pillow.

I understand that at one time pyheif-pillow-opener was necessary step and appreciate it. However since I don't see any activity in the repository I assume that there are no people who interested in further development (please, correct me if I wrong). 

I propose to add a description that the project is not on actively developed and optionally add a link to [heif-image-plugin](https://github.com/uploadcare/heif-image-plugin/).

With respect to your work, Alex.

**Comment by ciotto** [comment]
Hi @homm,
probably I have some problem with GitHub notification and I missed some PR.

However, I'm pleased to be the seed of something great and I'm happy to update the description in order to help users to find your work.
