### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jtressle** [ciotto/pyheif-pillow-opener#14]
Hi,

Thanks for developing this extension to Pillow.  I had a question regarding performance converting a .heic to a .jpg file.  Running `heif-convert` is about twice as fast as doing:

```
import pillow_heif.HeifImagePlugin

img = Image.open(path_heic)
img.save(path_jpg)
```

Is this expected?  For 100 images, `heif-convert` took 42 seconds, pillow_heif took 75 seconds (threaded), and 208 seconds using one thread.

Thanks,

**Comment by bigcat88** [comment]
This is not a valid place.
Ask here for `pillow-heif`:
[bigcat88/pillow_heif](https://github.com/bigcat88/pillow_heif)
or this repo was moved here:
[uploadcare/heif-image-plugin](https://github.com/uploadcare/heif-image-plugin/)

And need an example of `heic` file on which you test.

**Comment by jtressle** [comment]
@bigcat88 thank you for the response.  I didn't read the updated readme.  Will close now.
